joomcode/e2ed

src/package/actions/asserts/assertNumbersAreApproximatelyEql.ts
src/package/actions/asserts/assertNumbersAreApproximatelyEqual.ts
src/package/actions/asserts/index.ts

add assertNumbersAreApproximatelyEqual

---

src/package/utils/getRandomIntegerInRange.ts
src/package/utils/index.ts

feat: add getRandomIntegerInRange

---

src/package/actions/pages/history/historyGoBack.ts
src/package/actions/pages/history/historyGoForward.ts
src/package/actions/pages/history/index.ts
src/package/actions/pages/index.ts

add historyGoBack historyGoForward actions

---

src/package/utils/getLocatorProperty.ts
src/package/utils/index.ts

add getLocatorProperty util

---

src/package/selectors/index.ts
src/package/selectors/locatorIdInParentSelector.ts

Issue Number: [WEB-6125](https://joom.myjetbrains.com/youtrack/issue/WEB-6125) Перенести testIdWithParentSelector в селекторы e2ed и переименовать

feat: add locatorIdInParentSelector

---

.eslintrc.yaml
autotests/config.ts
autotests/index.ts
autotests/tests/main/exists.ts
autotests/types/customPackProperties.ts
autotests/types/index.ts
bin/forks/testcafe-without-typecheck/transforms/setDependencies.sh
package-lock.json
package.json
src/createTestFunction.ts
src/types/config.ts
src/types/internal.ts
src/types/userland/index.ts
src/types/userland/placeholders.ts
src/utils/getFullConfig.ts

Added custom properties defined in the project to the pack config.
These properties will allow you to parameterize hooks, that is, change the behavior of hooks in different packs.
Also in this pull request, a description of the pack config fields (which are not part of the TestCafe config) has been added, and TestCafe has been updated to version 2.3.1, and eslint has been updated to version 8.34.0.

feat: Add custom pack properties

---

.eslintrc.yaml
autotests/doAfterPack.ts
autotests/hooks/getMainTestRunParams.ts
autotests/pageObjects/pages/Main.ts
autotests/types/packSpecific.ts
bin/forks/testcafe-without-typecheck/transforms/setDependencies.sh
package-lock.json
package.json
src/bin/splitImportsIntoAutotestsAndE2ed.ts
src/createLocator.ts
src/createTestId.ts
src/types/config/doBeforePack.ts
src/types/config/ownE2edConfig.ts
src/types/index.ts
src/types/report.ts
src/types/userland/createPackSpecificTypes.ts

Currently, e2ed does not have a recommended built-in method for marking test locators.
Now e2ed will have a built-in recommended method for marking locators in the form of a `create-locator` package.
Also in this pull request, a bug with pack-specific `LiteReport` type has been fixed.

feat: add create-locator

---

README.md
autotests/hooks/getLogContext.ts
autotests/mapLogPayloadInConsole.ts
autotests/packs/allTests.ts
bin/forks/testcafe-without-typecheck/transforms/setDependencies.sh
package-lock.json
package.json
src/actions/takeScreenshot.ts
src/constants/color.ts
src/constants/internal.ts
src/constants/log.ts
src/testcaferc.ts
src/types/config/ownE2edConfig.ts
src/types/log.ts
src/utils/events/registerEndE2edRunEvent.ts
src/utils/events/registerEndTestRunEvent.ts
src/utils/events/registerStartE2edRunEvent.ts
src/utils/exit/processExit.ts
src/utils/generalLog/getMessageWithBackgroundColor.ts
src/utils/generalLog/index.ts
src/utils/generalLog/logEndTestRunEvent.ts
src/utils/generalLog/logFile.ts
src/utils/generalLog/messages.ts
src/utils/generalLog/removeStyleFromString.ts
src/utils/retry/afterRetries.ts
src/utils/retry/processRetry.ts
src/utils/retry/updateRetriesStateAfterRetry.ts
src/utils/tests/runTests.ts

Some bugfixes and fixed in docs:
* fix: error with local run (because of testcafe-reporter-for-e2ed)
* docs: format of list in README.md
* docs: add example of mapLogPayloadInConsole
* feat: add assert-modules-support-case-insensitive-fs and assert-package-lock-is-consistent
* fix: code of mapLogPayload-functions in logs
* fix: write all general logs to pack logs file

fix: error with local run and skipped general logs in pack logs file

---

autotests/tests/request.ts
bin/forks/testcafe-without-typecheck/transforms/setDependencies.sh
package-lock.json
package.json
src/bin/runTestsSubprocess.ts
src/utils/retry/killTestCafeProcessesOccupyingPorts.ts
src/utils/retry/runRetry.ts

Prior to this pull request, tests retry could hang indefinitely.
Tests retry is now aborted if it hangs (if it doesn't respond within a certain time).
Also updated dependency versions and TestCafe version (to 2.6.2).

feat: end hung retry

---

package-lock.json
package.json
src/bin/splitImportsIntoAutotestsAndE2ed.ts
src/utils/fs/index.ts
src/utils/fs/logIsoString.ts
src/utils/fs/writeBrokenStatusToTestRunJsonFile.ts
src/utils/fs/writeFile.ts
src/utils/fs/writeTestRunToJsonFile.ts
src/utils/report/writeHtmlReport.ts
src/utils/report/writeLiteJsonReport.ts
src/utils/retry/runRetry.ts
src/utils/test/getTestFnAndReject.ts

fix: end hung retray in timeout by last log event date

---

src/utils/fs/logIsoString.ts
src/utils/retry/runRetry.ts

fix: reset last log event time on each retry

---

autotests/tests/waitForAllRequestsComplete.ts
package-lock.json
package.json
src/actions/waitFor/waitForAllRequestsComplete.ts
src/types/global.d.ts
src/utils/clone/cloneWithoutLogEvents.ts
src/utils/expect/Expect.ts
src/utils/report/client/addOnClickOnClass.ts
src/utils/report/client/render/renderStep.ts
src/utils/report/client/setReadJsonReportDataObservers.ts
src/utils/requestHooks/addContextToResultsOfClassCreateMethods.ts
src/utils/requestHooks/getRequestFromRequestOptions.ts
src/utils/waitForEvents/getUrlsByRequestHookContextIds.ts
src/utils/waitForEvents/index.ts

Add urls of not complete requests to logs (for `waitForAllRequestsComplete` function).
Update @typescript-eslint/* to 6.0.0.

fix(waitForAllRequestsComplete): add urls of not complete requests to logs

---

src/actions/waitFor/waitForAllRequestsComplete.ts
src/actions/waitFor/waitForRequest.ts
src/actions/waitFor/waitForResponse.ts
src/types/waitForEvents.ts
src/utils/waitForEvents/completeRequest.ts
src/utils/waitForEvents/processEventsPredicate.ts

Add wait time to all wait-for actions (`waitForAllRequestsComplete`, `waitForRequest`, `waitForResponse`).

feat: add wait time to all wait-for actions

---

README.md
autotests/packs/allTests.ts
autotests/tests/main/exists.ts
autotests/tests/notInAllTestsPack.ts
autotests/tests/request.ts
autotests/tests/waitForAllRequestsComplete.ts
autotests/tests/waitForRequest.ts
autotests/tests/waitForResponse.ts
package-lock.json
package.json
src/actions/waitFor/waitForAllRequestsComplete.ts
src/actions/waitFor/waitForInterfaceStabilization.ts
src/actions/waitFor/waitForRequest.ts
src/actions/waitFor/waitForResponse.ts
src/types/config/ownE2edConfig.ts
src/types/waitForEvents.ts
src/utils/waitForEvents/completeRequest.ts
src/utils/waitForEvents/processAllRequestsCompletePredicate.ts

feat: add `maxIntervalBetweenRequestsInMs` option to `waitForAllRequestsComplete` function (instead of `firstRequestTimeout`).
tests: add more tests for `waitForAllRequestsComplete` function.
refactor: use `E2edError` instead of `Error` in internal runtime tests

feat: add maxIntervalBetweenRequestsInMs option to waitForAllRequestsComplete

---

LICENSE
package-lock.json
package.json
src/getModulesGraph.ts
src/types/index.ts
src/types/utils.ts
src/utils/deepMerge.ts
src/utils/report/client/render/renderDuration.ts
src/utils/report/client/render/renderStep.ts
src/utils/report/client/render/renderTestRunDescription.ts
src/utils/report/render/renderRetryHeader.ts
src/utils/report/render/renderTestRunButton.ts

chore: update devDependencies (eslint, @typescript-eslint/*, etc)
fix: add type `FilePathFromRoot` to public API
fix: duration for long time intervals (in HTML report)
chore: update `get-modules-graph` to 0.0.9.
chore: update devDependencies (eslint, @typescript-eslint/*, etc).
fix: add type `FilePathFromRoot` to public API.
fix: duration for long time intervals (in HTML report).

chore: update `get-modules-graph` to 0.0.9

---

src/actions/takeScreenshot.ts
src/actions/waitFor/waitForAllRequestsComplete.ts
src/actions/waitFor/waitForRequest.ts
src/actions/waitFor/waitForResponse.ts
src/utils/clientFunction/getClientFunctionWithTimeout.ts
src/utils/promise/getPromiseWithResolveAndReject.ts
src/utils/promise/getTimeoutPromise.ts
src/utils/report/assertThatTestNamesAndFilePathsAreUniqueInOneRetry.ts
src/utils/test/getTestFnAndReject.ts
src/utils/test/runTestFn.ts

fix: error with option `timeout` of `takeScreenshot` action.
refactor: rename `promise` with timeout to `promiseWithTimeout`.
fix: more logs for duplicates of `filePath` and names of tests.

fix: error with option `timeout` of `takeScreenshot` action

---

CHANGELOG.md
autotests/configurator/mapBackendResponseToLog.ts
package.json
scripts/updateChangelog.ts

fix: typos in `CHANGELOG.md`.
fix: errors in `package.json` by `npm pkg fix`.
fix: simplify `mapBackendResponseErrorToLog` function.

fix: errors in `updateChangelog` script

---

Dockerfile
autotests/configurator/logFieldReplacer.ts
autotests/configurator/mapBackendResponseErrorToLog.ts
autotests/configurator/mapBackendResponseToLog.ts
package-lock.json
package.json
src/configurator/getReplacedObject.ts
src/configurator/index.ts
src/types/http/http.ts
src/utils/expect/createExpectMethod.ts
src/utils/index.ts
src/utils/requestHooks/RequestHookToWaitForEvents.ts

fix: message for failed assertion.
feat: add `duration` field to `ResponseWithRequest`.
fix: move some independent functions to `e2ed/configurator` from `e2ed/utils`.
chore: update alpine to 3.19.0.
fix: use latest version of nodejs, in which browser connection in Docker is stable.
fix: `replaceFields` function for objects with nontrivial prototypes.
chore: update devDependencies (`@types/node`, `@typescript-eslint/*`, etc).

fix: message for failed assertion

---

bin/forks/testcafe-without-typecheck/transform.sh
bin/forks/testcafe-without-typecheck/transforms/disableDisconnectReject.sh
bin/forks/testcafe-without-typecheck/transforms/enlargeDisconnectThreshold.sh
package-lock.json
package.json
src/types/extends.ts
src/utils/resourceUsage.ts
src/utils/test/getRunTest.ts

fix: do not reject retry if some browser disconnect.
fix: correct CPU cores metrics in resource usage util.
chore: update `@types/node` to 20.11.16.

fix: do not reject retry if some browser disconnect

---

.eslintrc.yaml
autotests/bin/runDocker.sh
autotests/tests/internalTypeTests/createPageObjectsFromMultiSelector.skip.ts
bin/dockerEntrypoint.sh
package-lock.json
package.json
src/utils/createPageObjectsFromMultiLocator.ts
src/utils/error/E2edError.ts
src/utils/selectors/createCustomMethods.ts

fix: restore field `params` in `E2edError`.
fix: case-sensitive of attributes names in custom selector methods.
chore: turn on more `@typescript-eslint/*` rules.
chore: update `devDependencies` (`typescript`, `@types/node`, etc).

fix: restore errors params

---

package-lock.json
package.json
src/actions/navigateToUrl.ts
src/actions/pages/reloadPage.ts
src/utils/request/request.ts
src/utils/test/processTestController.ts

fix: disable Service Workers on CDP mode.
fix: add `retry` field to error params in `request` util.
chore: update `devDependencies` (`@types/node`, etc).

fix: disable service workers on CDP mode

---

README.md
autotests/pageObjects/pages/Main.ts
autotests/selectors/rootLocator.ts
autotests/tests/internalTypeTests/createPageObjectsFromMultiSelector.skip.ts
package-lock.json
package.json
src/createLocator.ts
src/utils/report/render/rootLocator.ts
src/utils/retry/processRetries.ts
src/utils/retry/updateRetriesStateAfterRetry.ts

fix: `isLastRetrySuccessful` flag in CDP mode.
chore: update `devDependencies` (`@types/node`, `typescript`, etc).
chore: update `create-locator` to version 0.0.20 with new API.

fix: logic of ending of retries in CDP mode

---

autotests/configurator/fullMocks.ts
package-lock.json
package.json
src/createLocator.ts
src/types/fullMocks.ts
src/utils/fullMocks/enableFullMocks.ts

feat: add `writeOnly` flag to "full mocks" config.
chore: update `create-locator` and `devtools-protocol`.

feat: add `writeOnly` flag to "full mocks" config

---

src/utils/waitForEvents/isReRequest.ts

fix: ignore query parameters in re-requests for `waitForAllRequestsComplete`.

fix: ignore query parameters in re-requests

---

README.md
autotests/packs/allTests.ts
package-lock.json
package.json
src/types/config/ownE2edConfig.ts
src/types/index.ts
src/types/internal.ts
src/types/log.ts
src/utils/log/log.ts
src/utils/test/preparePage.ts
src/utils/waitForEvents/addNotCompleteRequest.ts
src/utils/waitForEvents/completeRequest.ts

feat: add `addLogsWithTags` field to pack config.
chore: update `prettier` to 3.4.2.

feat: add `addLogsWithTags` field to pack config

---

src/utils/waitForEvents/isReRequest.ts

fix: `isReRequest` respect `pathname`.

fix: `isReRequest` respect `pathname`

---

package-lock.json
package.json

chore: update `get-modules-graph` to 0.0.10.
chore: update Playwright to 1.49.1.
chore: update `@types/node`.

chore: update `get-modules-graph` to 0.0.10

---

package-lock.json
package.json

fix: circular dependency in `get-modules-graph` in CJS.

fix: circular dependency in `get-modules-graph` in CJS

---

.gitignore
autotests/tests/internalTypeTests/waitForEvents.skip.ts
autotests/tests/main/exists.ts
package-lock.json
package.json
src/actions/waitFor/waitForNewTab.ts
src/types/global.d.ts
src/utils/expect/createExpectMethod.ts

fix: selector description in `except`'s methods.
feat: add optional prepare step to `waitForNewTab` action.
chore: update Playwright to 1.50.0.
chore: update devDependencies (`@types/node`).

feat: add preparation step to `waitForNewTab` action

---

src/actions/waitFor/waitForNewTab.ts

fix: prepare step in `waitForNewTab` action.

fix: prepare step in `waitForNewTab` action

---

autotests/configurator/types/packSpecific.ts
src/utils/expect/toMatchScreenshot.ts
src/utils/report/client/render/renderTestRunDetails.ts
src/utils/report/client/render/renderTestRunError.ts

fix: support `toMatchScreenshot` in local runs.
fix: remove text style from error messages in HTML report.

fix: support `toMatchScreenshot` in local runs

---

autotests/configurator/matchScreenshot.ts
package-lock.json
package.json
src/types/matchScreenshot.ts
src/utils/expect/getScreenshotMeta.ts
src/utils/expect/toMatchScreenshot.ts
src/utils/packCompiler/getCompilerOptions.ts
src/utils/report/client/render/renderTestRunError.ts
src/utils/valueToString/removeStyleFromString.ts
tsconfig.json

fix: add more fields to screenshot metadata.
chore: update devDependencies (`@types/node`, `prettier`).

fix: add more fields to screenshot metadata

---

src/types/internal.ts
src/types/report.ts
src/utils/apiStatistics/addPageToApiStatistics.ts
src/utils/apiStatistics/addResponseToApiStatistics.ts
src/utils/apiStatistics/getBorderCount.ts
src/utils/apiStatistics/getUrlTemplate.ts
src/utils/apiStatistics/isIdentifier.ts
src/utils/events/registerEndE2edRunEvent.ts
src/utils/events/registerStartE2edRunEvent.ts
src/utils/exit/getExitCode.ts
src/utils/report/client/readPartOfJsonReportData.ts
src/utils/report/render/renderJsonData.ts

fix: merge API requests by replacing `id` to asterisks.
fix: save reports after errors in `doBeforePack`/`doAfterPack`.

fix: merge urls for API statistics

---

src/actions/setHeadersAndNavigateToUrl.ts
src/actions/waitFor/waitForRequest.ts
src/actions/waitFor/waitForResponse.ts
src/utils/events/calculateTestRunStatus.ts
src/utils/getGlobalErrorHandler.ts

fix: use `navigationTimeout` in `setHeadersAndNavigateToUrl`.
fix: timeout errors in `waitForRequest`/`waitForResponse`.
fix: do not fail run if caught `unhandledRejection` in test.

fix: do not fail run if caught `unhandledRejection` in test

---

autotests/actions/setPageCookiesAndNavigateToUrl.ts
autotests/actions/setPageRequestHeadersAndNavigateToUrl.ts
autotests/pageObjects/pages/E2edReportExample/E2edReportExample.ts
package-lock.json
package.json
src/Page.ts
src/actions/navigateToUrl.ts
src/actions/setHeadersAndNavigateToUrl.ts
src/types/index.ts
src/types/internal.ts
src/types/navigation.ts
src/types/utils.ts

feat: add `statusCode` property on pages.

feat: add `statusCode` property on pages
